### ISSUE TITLE
GalNet news images

### ISSUE THREAD

**Issue by Strayer** [charlesportwoodii/galnet-api#10]
It would be nice to also get the images of a GalNet article. I couldn't find a way to get these yet, sadly. It seems only the launcher and the game itself shows these images, neither the community page nor the "official" RSS has them.

This is the page the launcher loads for Horizon users:
http://hosting.zaonce.net/launcher/elite-dangerous-horizons/en.html

Maybe someone else has an idea about this.

I did some simple net logging of the game… not really sure, but maybe the GalNet is retrieved via api.orerve.net. All requests to that domain were done with HTTPS though and I didn't really want to fiddle with SSL decryption and the game.

**Comment by charlesportwoodii** [comment]
Just from a casual look:
```
http://hosting.zaonce.net/launcher/elite-dangerous-horizons/en.html
```
Is an AWS CloudFront to a Drupal site to:
```
http://launcher-4586754895.elitedangerous.com/en/horizons/pc
```
Frontier is _probably_ just using Drupal as a back end for the launcher, then converting it to a static site. I'm not seeing any of the normal Drupal stuff (like an RSS feed to pull down content). I doubt they're using the launcher to manage Galnet data anyways,

I know `api.orerve.net` is the main API (it's similar to the API used by the iOS companion app `companion.orerve.net`. There's a bunch of things you can do with that, but I haven't seen anything strictly related to Galnet, though I'm sure there's something in there for that. That would probably be the best way to retrieve images if they do exist. I don't think every galnet post has an image though.


Probably the best way to go about this would be to fire up MITMProxy (https://mitmproxy.org/) while ED is running and try to intercept the API endpoints used to fetching Galnet articles. I'd thought about doing that in the past but I never got around to it (haven't played ED in a while). If someone can fetch the correct API endpoint for Galnet articles I could switch it over to that.

**Comment by Strayer** [comment]
> Probably the best way to go about this would be to fire up MITMProxy

I agree. I'm a little hesitant about this though, as this *might* warrant actions against the account since one has to man-in-the-middle the TLS connection ;) Easiest way would probably be to use the Mac-client, as mitmproxy doesn't support transparent proxying on Windows. Maybe another tool works though.

Anyway, I'm pretty sure that the API will require some kind of authentication token, making the whole thing much more complicated.

I guess the efforts to get this working are way too high for the benefit, but maybe someone has a better idea for this.
